# External Secrets Operator - ExternalSecret example
# Syncs secrets from OpenBao to Kubernetes

apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openbao-example
  namespace: external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: openbao-backend
    kind: SecretStore
  target:
    name: example-sync
  data:
  - secretKey: asdf
    remoteRef:
      key: gke-infra-non-prod/tenant-1/asdf
      property: asdf
